### ISSUE TITLE
No license specified in the code

### ISSUE THREAD

**Issue by lphuberdeau** [alexsdutton/www-authenticate#1]
BSD [according to pypi](https://pypi.python.org/pypi/www-authenticate/0.9.1).

**Comment by erinn** [comment]
Could this be committed and closed out? I am trying to package this for Fedora/EPEL and need a license file (I believe).

**Comment by danc86** [comment]
@erinn python-www-authenticate is already in Fedora and EPEL7:
https://src.fedoraproject.org/rpms/python-www-authenticate

But it would be nice to get this merged for completeness.

**Comment by erinn** [comment]
Hmm I see the EPEL 7 branch but I can't seem to find the package actually in the EPEL repo. Hence my confusion here, but I certainly do see it in Fedora, thanks for pointing that out.

**Comment by theMarix** [comment]
This is also a problem for my usage of the library. Which is especially an issue as `pantsbuild.pants` now depends on it. In addition, BSD has many variants, so having a generic BSD declaration instead of an explicit license text is suboptimal.

**Comment by alexdutton** [comment]
Argh, sorry for neglecting this! I will get the license PR merged :-)

**Comment by alexdutton** [comment]
License PR merged, so I'll close this now. I'll look through #3 and then look to make a release.
